# TODOs: add linkedin
title: JJukE's Homepage
name: Sangjune Park
email: psj9116@unist.ac.kr
description: >-
  Ph.D Candidate


baseurl: ""
url: "https://jjuke.github.io"


# profile image
profile_image: images/me.JPG


# Contacts, Links
email_address: psj9116@unist.ac.kr
linkedin_url: https://www.linkedin.com/in/sangjune-park-463178287/
github_url: https://github.com/jjuke
instagram_url: https://www.instagram.com/jjuke_sangjune
blog_url: https://jjuke-brain.tistory.com/

# Custom Color
primary: AE4143 #A42B2C #2c98f0 #b72cf0
primary_hover: 44A4F2 #9a2dc7
color_1: 2c98f0 #b72cf0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 4054b2
color_red: 7F172B
color_navy: 001B54


# About
about_meta: About Me
about_content: >-
  I'm starting my Ph.D. journey in the <a href=https://unist.info/>3D Vision and Robotics Lab</a> at UNIST, advised by Prof. Joo. <br>
  My research lies at the intersection of 3D Vision and Robotics, driven by a passion for bridging software-level 3D understanding with real-world hardware applications.
  Specifically, I have been deeply interested in multi-modal 3D generative models for objects, scenes and humans, and plan to extend it to simulators, and finally real-world operators such as robot arms and humanoids. <br>
  I am continuously striving to advance my research skills and contribute to the field. <br>
# about_services: # 형식에 맞추어 항목 추가
# - icon: icon-data
#   name: Data Mining
# - icon: icon-monitor
#   name: ML, DL, RL
# - icon: icon-phone3
#   name: Mechanical ENG
# - icon: icon-code
#   name: Python, C++
about_box_content: Please refer to my CV for more details 😁

about_box_content_color: rgb(255, 255, 255)

about_box_button:
  link: pdf/cv_260323.pdf
  name: CV


# # Tech  skill
# tech_meta: TECH SKILLS
# tech_header: 제 역량은 다음과 같습니다.
# tech_content:
# tech_list: # 형식에 맞추어 항목 추가
# - name: >-
#     Python, PyTorch <br><br>
#   color: color-1
#   animation: fadeInLeft
#   percent: 80
#   mark: 80
#   content: >-
#     파이썬 기초, 데이터 분석, 시각화를 공부하고 파이썬 언어의 기본적인 문법에 대해 알고 있으며, 자료구조 및 알고리즘을 파이썬으로 공부하였습니다.
#     석사과정을 시작하면서 PyTorch를 익혀 연구에 활용하고 있습니다. <br><br>

# - name: >-
#     Visual SLAM <br><br>
#   color: color-2
#   animation: fadeInRight
#   percent: 60
#   mark: 60
#   content: >-
#     소속 연구실의 주요 분야 중 하나로, 공부하면 할수록 해당 분야가 정말 방대하고 제가 아는것이 극히 일부분이라는 것을 많이 느낍니다.
#     많은 사람들이 편안하고 안전한 삶을 영위하도록 하는 로보틱스 기술의 눈과 뇌를 책임지기 위해 많은 공부를 하고 있습니다. <br><br><br><br>

# - name: >-
#     3D Vision <br><br>
#   color: color-3
#   animation: fadeInLeft
#   percent: 80
#   mark: 80
#   content: >-
#     소속 연구실의 주요 분야 중 하나로, 말그대로 한 차원 업그레이드된 컴퓨터 비젼 연구를 진행중입니다.
#     자율주행에 관심을 갖던 학부생 때부터 Pointcloud를 활용한 인지 시스템에 관심이 있었으며, 
#     현재는 3D Scene Graph 관련 연구를 진행중입니다.<br><br>

# - name: >-
#     Github, Docker <br><br>
#   color: color-4
#   animation: fadeInRight
#   percent: 30
#   mark: 30
#   content: >-
#     일부 프로젝트를 진행할 때 github로 소스 코드를 관리하였으며, 협업 역시 github을 통해 진행하였습니다.
#     또한 github서버를 활용하여 포트폴리오 사이트를 관리합니다.
#     그리고 서버와 Docker를 활용하여 연구를 진행하고 있습니다. <br><br>

# tech_desc: 최종 목표인 Top tier 논문 작성을 위해 <strong>Scratch로 논문을 구현해낼 수 있을 정도의 코딩 실력과, 다양한 논문의 insight를 아이디어로 승화시키는 역량을</strong>계속해서 키울 것입니다.


# PUBLICATIONS
pub_meta: My Work
pub_header: PUBLICATION
pub_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:)    # 더보기 내용
pub_load_more_url: #

pub_3dvision_name: 3D Vision
pub_3dvision: # 형식에 맞추어 항목 추가
- background_url: pub_materials/1_NotLikeTransformers.gif
  animation: fadeInLeft
  name: "Not Like Transformers: Drop the Beat Representation for Dance Generation with Mamba-Based Diffusion Model"
  project_page_url: https://vision3d-lab.github.io/mambadance/
  paper_url: https://openaccess.thecvf.com/content/WACV2026/html/Park_Not_Like_Transformers_Drop_the_Beat_Representation_for_Dance_Generation_WACV_2026_paper.html
  arxiv_url: https://arxiv.org/abs/2603.08023
# - background_url: pub_materials/1_NotLikeTransformers.gif
#   animation: fadeInLeft
#   name: "Not Like Transformers: Drop the Beat Representation for Dance Generation with Mamba-Based Diffusion Model"
#   project_page_url: https://vision3d-lab.github.io/mambadance/
#   paper_url: 
#   arxiv_url: https://arxiv.org/abs/2603.08023


# # Robotics 논문도 낸다면..?
# pub_robotics_name: Robotics
# pub_robotics: # 형식에 맞추어 항목 추가
# - background_url: images/lab_project2.jpg
#   animation: fadeInRight
#   name: 스마트팩토리용 실감형 AR 인터렉티브 콘텐츠 플랫폼 개발(ing)
#   description: 메타버스 시대에 발맞춰 Capstone Design에서 VR Interactive Platform을 개발하였던 것과 연동하여 스마트팩토리를 위한 플랫폼을 개발한다.
#   detail_url: #
#   readmore_url: #


# Honors
hon_meta: Achievement
hon_header: HONOR
hon_services: # 형식에 맞추어 항목 추가
# - name: 매니지먼트
#   color: color-1
#   icon: icon-bulb
#   content: 학부 과정동안 진행한 9개 중 8개의 과목 텀 프로젝트에서 팀장을 맡아 각 팀원들의 능력을 파악하고 업무를 배정하고 관리하였습니다.
# - name: 기술습득
#   color: color-2
#   icon: icon-home
#   content: 제가 선택한 길, 항상 열정을 다해 공부하며 새로운 기술에 대해 즐거운 마음으로 배웁니다.
# - name: 프로젝트
#   color: color-3
#   icon: icon-phone3
#   content: 다양한 프로젝트를 기획, 진행 해왔기에 업무에 대한 협력과 배분이 익숙합니다. 새로운 프로젝트에 도전적입니다.
# - name: 기타 Tool 활용 능력
#   color: color-4
#   icon: icon-monitor
#   content: NX, Inventor, Solidworks 등의 3D 설계 툴, ANSYS 해석 툴, MATLAB, Arduino와 같은 Tool 사용에 능숙하며, C, Java, Swift, C#, Scala 언어를 다뤄본 경험이 있습니다.
hon_counters:
- name: papers
  count: 1
  speed: 2000
- name: honors
  count: 0
  speed: 2000


# Career
career_meta: experience
career_header: CAREER
career_list:
# - name: UNIST Master's Course
#   date: 2022.09~
#   content: RVI(Robotics and Visual Intelligence) Lab에서 연구중
#   color: color-4
#   icon: icon-pen2
#   animation: fadeInLeft
# - name: Realistic AR Interactive Contents for Smart Factory (학부 연구실 산학 협력 과제)
#   date: 2020.01~2022.06
#   content: 실감형 원격 교육, System Engineer와 현장 작업자 간 협업 Contents, Simulation, 정밀도 프로그램을 포함하는 VR Interactive Platform 개발
#   color: color-4
#   icon: icon-pen2
#   animation: fadeInLeft
# - name: Spindle Appraisal Project (학부 연구실 과제)
#   date: 2019.10~2022.06
#   content: Spindle 역설계<br> 센서 신호 FFT 변환<br> 이상 신호 감지를 위한 Clustering (팀 프로젝트와 연동) - 진행중
#   color: color-3
#   icon: icon-pen2
#   animation: fadeInLeft
# - name: 현대자동차 (Contract Worker)
#   date: 2018.08~2019.02
#   content: 현대자동차 울산공장에서 의장, 도장 등의 현장직 일을 맡아 자동차가 완성되어가는 과정을 몸소 경험
#   color: color-2
#   icon: icon-spanner
#   animation: fadeInLeft
# - name: PNP Engineering (Part Time Job)
#   date: 2017.12~2018.02
#   content: 자동차 샤시 부품 연구를 위한 Setting (공구를 사용한 분해/조립, 센서 부착 등)<br> 현대자동차 남양연구소에서 부품 연구 과정 경험
#   color: color-1
#   icon: icon-spanner
#   animation: fadeInLeft
- name: Ulsan National Institute of Science and Technology
  date: 2024.09~
  content: Researching at 3D Vision and Robotics Lab in UNIST Graduate School of Artificial Intelligence.
  color: color-3
  icon: icon-pen2
  animation: fadeInLeft
- name: Ulsan National Institute of Science and Technology
  date: 2022.09~2024.08
  content: Achieved Master's Degree at 3D Vision and Robotics Lab in UNIST Graduate School of Artificial Intelligence.
  color: color-2
  icon: icon-pen2
  animation: fadeInLeft
- name: Seoul National University of Science and Technology
  date: 2015.03~2022.08
  content: Achieved Bachelor's Degree in both Mechanical Design and Automation Engineering and ICT Artificial Intelligence Program
  color: color-1
  icon: icon-pen
  animation: fadeInLeft


# # Education
# edu_meta: Education
# edu_header: Education
# edu_list:
# - title: ULSAN NATIONAL INSTITUTE OF SCIENCE AND TECHNOLOGY
#   subtitle: UNIST AI대학원, Robotics and Visual Intelligence Lab
#   date: 2022.09 -
#   content: 석사과정
# - title: SEOUL NATIONAL UNIVERSITY OF SCIENCE AND TECHNOLOGY
#   subtitle: 서울과학기술대학교 기계시스템디자인공학과, ICT인공지능 연계전공
#   date: 2015.03 - 2022.08
#   content: 복수전공으로 졸업
# - title: ULSAN JOONGANG HIGH SCHOOL
#   subtitle: 울산중앙고등학교
#   date: 2012.03 - 2015.02
#   content: 과학중점고등학교


optional_front_matter:
  remove_originals:    true